### ISSUE TITLE
Version is not shown during flashing

### ISSUE THREAD

**Issue by TD-er** [esphome/esp-web-tools#108]
See: 
![image](https://user-images.githubusercontent.com/3751318/141287840-2414ec43-d514-4c51-bc15-bfd8946f0f89.png)

In the previous dialog, the "name" and the "version" were shown, in this dialog only the "name"
Previous dialog: 
![image](https://user-images.githubusercontent.com/3751318/141288512-60efe213-12cf-4652-a465-66ad7ae79504.png)

**Comment by balloob** [comment]
I did that on purpose. While installing, that information doesn’t matter anymore. Instead what matters is the progress.
