### ISSUE TITLE
No error dialog when com port cannot be opened

### ISSUE THREAD

**Issue by TD-er** [esphome/esp-web-tools#113]
![image](https://user-images.githubusercontent.com/3751318/141300595-df0035ff-4365-47e5-aedb-068f699956b0.png)

The com port is locked (I opened a Putty session to reproduce it) and pressed "Install"
Then accepted the pop-up to connect to the COM port and nothing seems to happen.
The error is present in the console, but no dialog is shown to indicate to the user what went wrong.

**Comment by balloob** [comment]
Ah snap. We filter out errors at that point in time because the exception usually is because users pressed “Cancel” instead of picking a port. I’ll take a look if we can differentiate the errors.

**Comment by balloob** [comment]
Looks like `AbortError` should be treated differently https://developer.mozilla.org/en-US/docs/Web/API/Serial/requestPort#exceptions
