### ISSUE TITLE
Should be able to set timeout for improv response after flash

### ISSUE THREAD

**Issue by amandel** [esphome/esp-web-tools#135]
Thanks for developing improv and the eco system around this.

Our [OpenBikeSensorFirmware](https://github.com/openbikesensor/OpenBikeSensorFirmware) takes quiet a bit of time during the initial startup (ssl cert is created, wifi connection is looked up, etc.). So the 1 or 10 seconds the esp-web-tools are waiting for  the 1st improv message are not enough. 

Could the timeout be exposed as an option? 

https://github.com/esphome/esp-web-tools/blob/0266057a383aa30e5ab0b33efb930af1eb41a55c/src/install-dialog.ts#L703

**Comment by balloob** [comment]
Is even 10 seconds not enough? 😱 

My initial idea was to just always wait 10s https://github.com/esphome/esp-web-tools/compare/always-delay

**Comment by amandel** [comment]
Unfortunately not I did not measure the time (will do) but creating the SSL certificat can take a minute.

**Comment by amandel** [comment]
Thanks a lot for adding this.
