### ISSUE TITLE
Support none-ESP devices

### ISSUE THREAD

**Issue by Park0** [esphome/esp-web-tools#149]
It would be nice to be able to install / update my whole fleet of devices. For this it would be nice if arduino devices could be updated / installed as well. 

Here is a similar project that did this:
https://github.com/kaelhem/avrbro (stk500v1)
https://github.com/noopkat/avrgirl-arduino

Would this be something that could be integrated in this project?

**Comment by balloob** [comment]
That's not something we're currently considering on adding ourselves but a pull request is welcome.
