### ISSUE TITLE
Problems flashing ("Amica") NodeMCU with CP2101

### ISSUE THREAD

**Issue by degraafm76** [esphome/esp-web-tools#156]
I have a couple of ("Amica") NodeMCU with CP2101 that i cannot flash with ESP web tools. 
![20220105_122248300_iOS](https://user-images.githubusercontent.com/1271011/148217274-46e32b67-6533-4c4b-89f4-90b994c7144a.jpg)

![image](https://user-images.githubusercontent.com/1271011/148208849-bf1127e4-ac59-4274-86a7-231b6b95a957.png)

Flashing the same NodeMCU's with Arduino IDE or PlatformIO is working fine:

![image](https://user-images.githubusercontent.com/1271011/148209314-0d57a6ce-3b84-43e0-b73f-acd253120ec6.png)

I allready tried different browsers/computers

**Comment by balloob** [comment]
Could it be the baud rate? 

ESP Web Tools defaults to 115200 baud rate: https://github.com/esphome/esp-web-tools/blob/main/src/connect.ts#L21

**Comment by degraafm76** [comment]
While the bottom of the NodeMCU states 9600 baud rate the upload speed in arduino IDE and PlatformIO is 115200 and working fine. I changed the baud rate to 9600 in esp web tools but uploading doesnt work. Openening the serial console through esp webtools does work , so the serial connection seems to be ok.

I browsed through the issue list and found https://github.com/esphome/esp-web-tools/issues/27. It seems there is a problem with uploading to ESP8266EX. This chip is on the boards i have. In this issue there are 2 problems described and it seems uploading to ESP8266EX is never solved.

If helpfull I can send you a board.

**Comment by ldijkman** [comment]
Hello 
i have 2 of these nodemcu boards = ESP 12E
no problem with my esp web tools installer https://ldijkman.github.io/randomnerd_esp32_wifi_manager/Touch_Electra-Electra_Touch/

also have wemos uno sized ESP 12F wich also works ok installing

today i recieved 5 wemos d1 mini ESP12F and that does not work
looks like the code bin part is done at 26% and then the littlefs part "Timed out waiting for packet header" 
code is running if i look at serial monitor (but it has no littlefs files)

made a littlefs bin adress 0x200000 button on webpage works ok on nodemcu esp12E and wemos uno sized 12F

but does not work for wemos D1 mini ESP12F

cannot figure out yet what is the problem

**Comment by ldijkman** [comment]
https://esphome.github.io/esp-web-tools/
tryed the install 
worked on my amica nodemcu ESP8266 / ESP12E (nice the improv configure wifi ! )
wemos d1 mini ESP12F also worked

**Comment by ldijkman** [comment]
changed the baudrate in local js file to 57600 now it installs littlefs bin at 0x200000 on wemos d1 mini esp12F

https://github.com/ldijkman/randomnerd_esp32_wifi_manager/issues/28

https://ldijkman.github.io/randomnerd_esp32_wifi_manager/Touch_Electra-Electra_Touch/local_js.html

**Comment by degraafm76** [comment]
with the latest version flashing ("Amica") NodeMCU with CP2101 is working

**Comment by rbric** [comment]
Same issue... I moved the VIN pin to the RST pin. It connected and flashed. In case someone is stuck also
