### ISSUE TITLE
Setting "new_install_prompt_erase" to true not working as expected for me

### ISSUE THREAD

**Issue by witnessmenow** [esphome/esp-web-tools#179]
Judging by #102 , setting `new_install_prompt_erase` to true, should allow the user the option of skipping erasing the flash, but that is not happening for me. I must be doing something wrong, but I'm not sure what.

Using this Manifest:
https://github.com/witnessmenow/SmarterEveryDayMatrix/blob/main/Webflash/WebVersion/bins/manifest.json

When I click install I get brought straight to this page, with no option to not erase the flash

![image](https://user-images.githubusercontent.com/1562562/154342807-c948e3af-8f70-4952-b6e4-57ef0c307fdd.png)

And I can confirm the flash is erased on install

Thanks

**Comment by balloob** [comment]
`new_install_prompt_erase` has to be set at a manifest level, not at a build level.

See docs at https://esphome.github.io/esp-web-tools/#manifest

**Comment by wilson3682** [comment]
use this instead, it is working for me:
"new_install_skip_erase": false,

as
