### ISSUE TITLE
Javascript error in case of integration to an individual website

### ISSUE THREAD

**Issue by redakker** [esphome/esp-web-tools#185]
Hi,

I would like to implement my own uploader so I've created a small website:
```html
<html>
    <head>
        <script type="module" src="https://unpkg.com/esp-web-tools@7.1.0/dist/web/install-button.js?module"></script>
    </head>
    <body>
        <esp-web-install-button manifest="manifest.json"></esp-web-install-button>
    </body>
</html>
```

I have the manifest file:
```
{
  "name": "MyAPP",
  "version": "1.0",
  "builds": [
    {
      "chipFamily": "ESP32",
      "parts": [
        { "path": "1.0.bin", "offset": 0 }
      ]
    }
  ]
}
```

Connect button appears, and I can see my ESP32 board, but when I choose the board I get an error:

![image](https://user-images.githubusercontent.com/15798619/156568837-13a591cb-29e9-4fd3-a0f8-c82291f050d0.png)

Do you know what could be the problem and how can I fix it?
I use Chrome  98.0.4758.102

Thanks!

**Comment by redakker** [comment]
Manifest file is downloaded with no problem

![image](https://user-images.githubusercontent.com/15798619/156569631-1ca92faa-3b6c-47ea-a90d-75acb6920a4d.png)

**Comment by balloob** [comment]
Unable to reproduce this.

In Chrome dev console -> sources, enable "Pause on excecptions" (pause button on a stop board) and run it again. It will now break when the error occurs and you can inspect the manifest variable to see what was loaded.

![image](https://user-images.githubusercontent.com/1444314/157187702-a2da73cd-871c-40c4-baf5-a356aef3d3f7.png)

The network tab will also show what was fetched, make sure the "response" matches the data that you expect.

**Comment by redakker** [comment]
@balloob 
I cannot reproduce anymore. Mabe because of the recent code changes.
Now it is working.
Thank you for your answer!
You can close the ticket
