### ISSUE TITLE
S3 flashing does not work with esp-web-tools

### ISSUE THREAD

**Issue by Jason2866** [esphome/esp-web-tools#203]
Flashing the S3 via ESP-WEB-Flasher does work fine.

When using Esp-web-tools it does not work. I have no idea what is going wrong.

Repo with test setup: [https://github.com/Jason2866/esp-web-tools](https://github.com/Jason2866/esp-web-tools) and the flash page [https://jason2866.github.io/esp-web-tools/](https://jason2866.github.io/esp-web-tools/)

**Comment by balloob** [comment]
Can you elaborate "does not work"? Screenshots? Browser console logs?

**Comment by Jason2866** [comment]
https://jason2866.github.io/esp-web-tools/

Seems init of device fails.

**Comment by Jason2866** [comment]
Chip S3 is detected correctly in Webflasher(Chip Name and Family).
I have no idea why this is not working when called from webtools. All other MCU types do work!

**Comment by balloob** [comment]
We need to update https://github.com/esphome/esp-web-tools/blob/main/src/util/chip-family-name.ts

**Comment by Jason2866** [comment]
Did [this change already](https://github.com/Jason2866/esp-web-tools/blob/main/src/util/chip-family-name.ts), does not solve.

**Comment by balloob** [comment]
That error is shown when:
1. We get the chip family name in ESP Web Tools format ([source](https://github.com/esphome/esp-web-tools/blob/main/src/flash.ts#L63))
2. We find a build in the manifest that matches the ESP Web Tools chip family name ([source](https://github.com/esphome/esp-web-tools/blob/main/src/flash.ts#L88))
3. If build not found, show not supported error ([source](https://github.com/esphome/esp-web-tools/blob/main/src/flash.ts#L96))

**Comment by balloob** [comment]
Do you use `ESP32-S3` as your chip family in your manifest.json? hmm it looks like you do https://github.com/Jason2866/esp-web-tools/blob/main/manifest/unofficial.tasmota32.manifest.json#L8

**Comment by balloob** [comment]
It should log the found chip family to your browser console

**Comment by Jason2866** [comment]
<img width="542" alt="Bildschirmfoto 2022-03-25 um 11 49 26" src="https://user-images.githubusercontent.com/24528715/160107300-dfc0fcad-421e-457d-a0c1-a4c3abbe05b8.png">
<img width="403" alt="Bildschirmfoto 2022-03-25 um 11 49 37" src="https://user-images.githubusercontent.com/24528715/160107305-2ede5487-b3df-49ac-8adb-4003efb91b77.png">

**Comment by balloob** [comment]
Checked and everything seems fine:

- [Your manifest has an `ESP32-S3` build](https://jason2866.github.io/esp-web-tools/manifest/unofficial.tasmota32.manifest.json)
- [Your ESP Web Tools build](https://jason2866.github.io/esp-web-tools/dist/web/connect-8b802612.js) has support for S3 in `getChipFamilyName`
- The console log shows that it's detecting it as `ESP32-S3`

btw, can you ping me on Discord? Might be faster to communicate to figure it out. I'm `balloob#6041`

**Comment by balloob** [comment]
Can you make sure that in the network tab the "Disable cache" checkbox is checked and you're not looking at an old version of the manifest?

**Comment by Jason2866** [comment]
I reworked web-flasher https://github.com/NabuCasa/esp-web-flasher/pull/108
Now it works :-)
Did a local build. You can try under https://jason2866.github.io/esp-web-tools/

**Comment by balloob** [comment]
I can't try yet because I don't have an S3. Just ordered one though! 

Fix released in https://github.com/esphome/esp-web-tools/releases/tag/7.3.1

Let me know if it works.

**Comment by Jason2866** [comment]
Going crazy....  Using the released version, i get the same error. When i put all packages local (in the repo) it does work.
The used versions are same.

**Comment by Jason2866** [comment]
Tooo late, **works!!** I forgot to update in index.html....
Thx for your help, and this great tool

But now really bedtime
