### ISSUE TITLE
install and then?

### ISSUE THREAD

**Issue by tcurdt** [esphome/esp-web-tools#21]
I tried both

https://www.home-assistant.io/blog/2021/06/16/power-up-your-esp-projects/
https://esphome.github.io/esp-web-tools/

it installs a generic esp8266 (although it is a NodeMCU) just fine - but then nothing happens.

When I press "Connect to Wifi"

https://www.home-assistant.io/blog/2021/06/16/power-up-your-esp-projects/

it scans - but there are no devices to pair.

**Comment by balloob** [comment]
ESP8266 devices do not have bluetooth and so are not able to use Improv. You will need to find their Wi-Fi access point and configure their Wi-Fi like that. We're working on making that process smoother.

**Comment by tcurdt** [comment]
@balloob makes sense - but it would be great to point that out after the install.

**Comment by balloob** [comment]
The ESP Web Tools website is a page aimed for developers to learn about the button. It's not actually meant to use as a place to install firmware. I think that such instructions would be great to add to places where it's used.

**Comment by tcurdt** [comment]
I got this working on one nodemcu ... another one now is just stuck at "erasing device"

![Screen Shot 2021-06-18 at 19 19 03](https://user-images.githubusercontent.com/13697/122596418-1f968100-d06a-11eb-950e-de45baa91c7a.png)

Any thoughts?

**Comment by TD-er** [comment]
> I got this working on one nodemcu ... another one now is just stuck at "erasing device"
> 
> ![Screen Shot 2021-06-18 at 19 19 03](https://user-images.githubusercontent.com/13697/122596418-1f968100-d06a-11eb-950e-de45baa91c7a.png)
> 
> Any thoughts?

What kind of module is it?
NodeMCU with CP2102 chip?
Something like this one?
![image](https://user-images.githubusercontent.com/3751318/122596936-ea3e6300-d06a-11eb-89db-fee22d1a682a.png)

**Comment by tcurdt** [comment]
I have have two. One works. One got/gets stuck during erasing.
![working](https://user-images.githubusercontent.com/13697/122598707-7b163e00-d06d-11eb-8da7-75bd20ede6f9.jpg)
![not-working](https://user-images.githubusercontent.com/13697/122598716-7ea9c500-d06d-11eb-996a-b740a449ff39.jpg)

**Comment by TD-er** [comment]
Those have a CH340 USB to uart chip.
But the ESP module itself is one  not from Espressif, but the module is an AI-Thinker, which I believe is the same as I have. (only different revision)

So maybe it is a timing issue then.
Your board is also relatively old, as is the batch I am having troubles with.

**Comment by tcurdt** [comment]
@TD-er If there is anything I can do to help to debug this - let me know.

**Comment by TD-er** [comment]
I think @balloob has way more experience in this
