### ISSUE TITLE
How to count the number of succesfull installs

### ISSUE THREAD

**Issue by ldijkman** [esphome/esp-web-tools#228]
Hello

do you know how  to count the number of succesfull installs

would like to know how much it is used succesfull

https://ldijkman.github.io/randomnerd_esp32_wifi_manager/Touch_Electra-Electra_Touch/

**Comment by ldijkman** [comment]
stays in my mind

i think the end "succes image" is not showed
would it be possible to choose an end "succes image" at the end
an choose image location in json file or button code

**Comment by ldijkman** [comment]
![2022-05-14-073842_1920x1080_scrot](https://user-images.githubusercontent.com/45427770/168412359-8a735d07-44f3-465d-b1e9-9b02d4cfb6c3.png)

**Comment by balloob** [comment]
I don't want to allow customizing the ESP Web Tools UI. Instead you should implement Improv, it will allow you to let the user navigate to a website once connected to wifi. There you can show anything you want.
