### ISSUE TITLE
Initialize fails with D1 mini ESP32

### ISSUE THREAD

**Issue by Stefan-van-Hattum** [esphome/esp-web-tools#243]
Hi,

I can't seem too install the firmware with Web-ESPHome on a D1 mini ESP32. It can connect and when I select the firmware and hit install it says connecting and after a while it gives the message "Initialize fails" .
Unfortunately there is no logging of some sort to see what exactly goes wrong, perhaps that might be added in future release ?
It does not have a flash button on it but with other boards like the ESP8266 D1 mini and NodeMCU both ESP8266 and ESP32 there was no need to use the flash button with Web-ESPHome.

**Comment by Jason2866** [comment]
Use web-tools version >=8. There is no check anymore for magic bytes.
