### ISSUE TITLE
Clarification of "boot button" and when to press it

### ISSUE THREAD

**Issue by hagenbuch** [esphome/esp-web-tools#253]
Dear all, 

I have to thank you very much, it's fantastic that we are having the web installer!

I managed to open a "Nous A1" (alias Gosund SP111 1.1 as I read on the PCB) and managed to connect it to my FTDI converter with 3.3 Volt, blue LED is blinking. The device still has the original firmware and has never seen the app.

I'd like to install Tasmota and yes, I do see the right serial port on my Linux Mint. TX / RX lines are crossed between device and FTDI. Blue light is blinking.

However, I do find THE button but I have no idea if there should be a second "reset button" or if I have to solder something onto some GPIO, pull it to GND or Vcc in the process. Also: I do not know when exactly to press the button and for how long.

The log says:

```
[notice]mqtt_client.c:590 gw wifi stat is:2
[notice]mqtt_client.c:590 gw wifi stat is:2
[notice]mqtt_client.c:590 gw wifi stat is:2
[notice]mqtt_client.c:590 gw wifi stat is:2
```

but this ends when I unplug the device. I don't understand, I thought this works over USB and not Wifi.

The only thing the web installer (Chromium in Linux Mint) tells me is this:

"Failed to initialize. Try resetting your device or holding the BOOT button while clicking INSTALL."

On two Linux mint machines..

When I press the button longer, I see in the logs:

```
Fatal exception (0): 
epc1=0x4000e25d
epc2=0x00000000
epc3=0x40107580
epcvaddr=0x40108aec
depc=0x00000000
rtn_add=0x40255c86

Free Heap Size: 31616
Stack Point: 3fffa300
3fffa300: 00000000 00000000 3fff03b8 3fff0b24
3fffa310: 3fff0ad8 3fff0b30 3fff0b34 40255de0
3fffa320: 40101af4 402673f4 00000030 00000000
3fffa330: 3fffa370 40108278 00000000 00000000
3fffa340: 00000000 00000000 00000000 00000000
3fffa350: 00000000 00000000 00000000 40267400
3fffa360: 00000000 00000000 00000000 00000000
3fffa370: 00000000 a5a5a5a5 40109a10 00005c78
 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x40100000, len 2592, room 16 
tail 0
chksum 0xf3
load 0x3ffe8000, len 764, room 8 
tail 4
chksum 0x92
load 0x3ffe82fc, len 676, room 4 
tail 0
chksum 0x22
csum 0x22

2nd boot version : 1.7(5d6f877)
SPI Speed : 40MHz
SPI Mode : DOUT
SPI Flash Size & Map: 8Mbit(512KB+512KB)
jump to run user1 @ 1000
Terminal disconnected: BreakError: A break condition has been detected.
```
Same on Chrome on Windows.

Also, I'm a little afraid if I brick the device by not having an antenna connected: I had to unplug it.

Now i soldered a button to the REST pin and ground on my Nous A1 but no combination of button presses seems to do the job.

Also, the Chip is ESP8285 so it should work, right?

Thankful for any help
Andreas

**Comment by balloob** [comment]
ESP8285 is not currently supported.
