### ISSUE TITLE
ESP8266EX Support?

### ISSUE THREAD

**Issue by ghtomcat** [esphome/esp-web-tools#27]
I can successfully flash my ESP32 but not my two NodeMCU (v2 and v3), which use the ESP8266EX Chip. 

error: "failed_initialize", details: Error: Unknown Chip

`esptool flash_id` returns:

```Serial port /dev/cu.usbserial-10
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: c4:5b:be:60:dc:da
Uploading stub...
Running stub...
Stub running...
Manufacturer: d8
Device: 4016
Detected flash size: 4MB
```

**Comment by TD-er** [comment]
I just tested it myself on a node that's not possible to flash using the web flasher:

![image](https://user-images.githubusercontent.com/3751318/123111470-3ad40880-d43d-11eb-8768-0218609c38c0.png)

```
esptool.py v3.0
Serial port COM3
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 2c:3a:e8:39:13:7c
```

<html>
<body>


Flash Chip ID: | Vendor: 0x20 Device: 0x4016
-- | --
Flash Chip Real Size: | 4096 kB
Flash IDE Size: | 4096 kB
Flash IDE Speed: | 40 MHz
Flash IDE Mode: | DOUT


</body>
</html>

**Comment by TD-er** [comment]
I added a breakpoint to where the exception was caught:
`domexception a framing error has been detected`

**Comment by conradopoole** [comment]
> I can successfully flash my ESP32 but not my two NodeMCU (v2 and v3), which use the ESP8266EX Chip.
> 
> error: "failed_initialize", details: Error: Unknown Chip
> 
> `esptool flash_id` returns:
> 
> ```
> Connecting....
> Detecting chip type... ESP8266
> Chip is ESP8266EX
> Features: WiFi
> Crystal is 26MHz
> MAC: c4:5b:be:60:dc:da
> Uploading stub...
> Running stub...
> Stub running...
> Manufacturer: d8
> Device: 4016
> Detected flash size: 4MB
> ```

Can you post what you see on Chrome's Developer console?

**Comment by conradopoole** [comment]
> I just tested it myself on a node that's not possible to flash using the web flasher:
> 
> ![image](https://user-images.githubusercontent.com/3751318/123111470-3ad40880-d43d-11eb-8768-0218609c38c0.png)
> 
> ```
> esptool.py v3.0
> Serial port COM3
> Connecting....
> Chip is ESP8266EX
> Features: WiFi
> Crystal is 26MHz
> MAC: 2c:3a:e8:39:13:7c
> ```
> 
> Flash Chip ID:	Vendor: 0x20 Device: 0x4016
> Flash Chip Real Size:	4096 kB
> Flash IDE Size:	4096 kB
> Flash IDE Speed:	40 MHz
> Flash IDE Mode:	DOUT

Is that all the console shows? No log messages?

**Comment by TD-er** [comment]
Yep that's all.

**Comment by conradopoole** [comment]
> Yep that's all.

Can you click on the login levels and enable Verbose?

<img width="675" alt="image" src="https://user-images.githubusercontent.com/5704796/123124112-afac4000-d447-11eb-8201-54d42d6d2197.png">

**Comment by TD-er** [comment]
Not much of a difference:
![image](https://user-images.githubusercontent.com/3751318/123127412-89d46a80-d44a-11eb-924b-639d125fe87b.png)

**Comment by ghtomcat** [comment]
> Can you post what you see on Chrome's Developer console?

It's empty, even with Verbose enabled. Do i need to do anything to have more debug output like @TD-er above?

**Comment by balloob** [comment]
By default it doesn't log to the console. I've just updated the demo to do so e6a198fefab3d16193bf797a51345716c96c82ab

**Comment by ghtomcat** [comment]
> By default it doesn't log to the console. I've just updated the demo to do so [e6a198f](https://github.com/esphome/esp-web-tools/commit/e6a198fefab3d16193bf797a51345716c96c82ab). So now open the chrome dev tools prior to flashing.

Thanks, now i see the following in the console (with the demo)

<img width="468" alt="Bildschirmfoto 2021-06-23 um 19 02 17" src="https://user-images.githubusercontent.com/361392/123138800-bcd02b80-d455-11eb-9a39-7533b49b8c36.png">

**Comment by TD-er** [comment]
![image](https://user-images.githubusercontent.com/3751318/123138659-9611f500-d455-11eb-8aab-e53c804b9bad.png)

This attempt I held GPIO-0 down and pressed reset.
The attempt before was the same, without reset + GPIO-0 held.

**Comment by balloob** [comment]
The error has been updated by @conradopoole. It should now include the magic value of your chip so we can add it to the detected list. The demo has been updated. 

@ghtomcat can you try it again and report the updated error message.

**Comment by ghtomcat** [comment]
> The error has been updated by @conradopoole. It should now include the magic value of your chip so we can add it to the detected list. The demo has been updated.

```start-flash-542f194f.js?module:1 Error: Unknown Chip: 0x-F3EFF```

**Comment by TD-er** [comment]
Me too, on one module (with CH340) Unknown Chip: 0x-F3EFF

The unresponsive unit with CP2102 USB to serial:
![image](https://user-images.githubusercontent.com/3751318/123157691-26a70000-d46b-11eb-9f96-94897c177403.png)

**Comment by balloob** [comment]
@ghtomcat this should be fixed in 3.4.2, live now in the docs. Can you try it?

**Comment by TD-er** [comment]
Does work with the node that gave the unknown chip error before.

The "timeout" unit still remains unresponsive, but had not expected it to be fixed by these changes.

**Comment by ghtomcat** [comment]
> @ghtomcat this should be fixed in 3.4.2, live now in the docs. Can you try it?

Works now, thank you!

**Comment by degraafm76** [comment]
> Me too, on one module (with CH340) Unknown Chip: 0x-F3EFF
> 
> The unresponsive unit with CP2102 USB to serial: ![image](https://user-images.githubusercontent.com/3751318/123157691-26a70000-d46b-11eb-9f96-94897c177403.png)

Did you get the CP2102 working? if have the same issue with ESP8266EX modules

**Comment by ghtomcat** [comment]
@degraafm76 yes, after the update it works for cp2102 and ch340

**Comment by degraafm76** [comment]
> @degraafm76 yes, after the update it works for cp2102 and ch340

I see, but not for ESP8266EX modules.
