### ISSUE TITLE
Update preparing firmware instructions

### ISSUE THREAD

**Issue by balloob** [esphome/esp-web-tools#299]
> @balloob @TD-er Changes ahead, latest Arduino ESP32 stage does not use anymore `*.bin` file for bootloader. The `*.elf` file builded with Arduino Lib Builder is used and converted to an `*.bin` file during compile of the main sketch. So no more wrong SHA message during boot of the ESP32x. Currently Platformio does not support yet.
See [issue.](https://github.com/espressif/arduino-esp32/issues/7572) This will be the standard way, with release of core 2.0.6.
So in a not so far future, for building a merged firmware, the creator has to do the `*.bin` build out of the `*.elf` bootloader file too.

_Originally posted by @Jason2866 in https://github.com/esphome/esp-web-tools/issues/298#issuecomment-1346193933_

**Comment by Jason2866** [comment]
Platformio build part needed has been updated and merged today in Arduino esp32 repo. Platformio crew has done it very user friendly, the builded and needed `partitions.bin` is in the same folder where the builded bin firmware sketch is.
```
    Offset | File
 -  0x1000 | /Users/hans/Git/Tasmota/.pio/build/tasmota32/bootloader.bin
 -  0x8000 | /Users/hans/Git/Tasmota/.pio/build/tasmota32/partitions.bin
 -  0xe000 | /Users/hans/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin
 -  0x10000 | /Users/hans/Git/Tasmota/.pio/build//tasmota32/firmware.bin
```
So for the user just the place where to look for the `partitions.bin`  has changed.

**Comment by balloob** [comment]
Since we didn't document where the user could find `bootloader.bin`, I guess this doesn't require any changes for our README?

**Comment by Jason2866** [comment]
Yep. Sometimes it is better not to document everything ;-)

**Comment by TD-er** [comment]
> Yep. Sometimes it is better not to document everything ;-)

That's my specialty :)
