### ISSUE TITLE
Angular import

### ISSUE THREAD

**Issue by joelinfo19** [esphome/esp-web-tools#305]
Hi, I've tried to use esp-web-tools in angular but I have a problem

I've installed esp-web-tools package with npm:
`npm i esp-web-tools`
I imported in file angular.json:

`"scripts": [
              "node_modules/esp-web-tools/dist/web/install-button.js"
            ]`
      
I was able to use the element html esp-web-install-button but I have an error in console 

![error](https://user-images.githubusercontent.com/52236148/211110997-df1a8bf4-6609-45a3-a607-24dda54cb126.png)

I saw in folder node_modules  from esp-web-tools and file connect-2f67c09e.js exist 

![node-modules](https://user-images.githubusercontent.com/52236148/211111344-bb401402-5d05-4529-ad14-0de01f93a8cf.png)

but it seems as if the browser could not locate this file.
Does anyone know what I'm doing wrong? or How to implement esp-web-tools in angular ?

Thanks

**Comment by balloob** [comment]
ESP web tools uses dynamic imports. If you refer to it as a script, it should be loaded as a module. If you follow the instructions from our website, you can use the tag in Angular just fine.

We are not familiar with Angular so not an issue we can help you with further.
