### ISSUE TITLE
Improv initialization failed.  Error:  Improv Wi-Fi Serial not detected

### ISSUE THREAD

**Issue by playground** [esphome/esp-web-tools#311]
I want to be able to prompt the user to change the WiFi upon flash completion.  I'm using AutoConnect and here is the manifest.json

`    {
      "chipFamily": "ESP32",
      "improv": false,
      "parts": [
        { "path": "wifi-ble/bootloader.bin", "offset": 4096 },
        { "path": "wifi-ble/partitions.bin", "offset": 32768 },
        { "path": "wifi-ble/boot_app0.bin", "offset": 57344 },
        { "path": "wifi-ble/firmware.bin", "offset": 65536 }
      ]
    }`

Is there a working example I can look at?

**Comment by balloob** [comment]
Your firmware needs to implement [Improv Wi-Fi over Serial](https://www.improv-wifi.com/) to offer connect it to Wi-Fi.
