### ISSUE TITLE
ESP32-S3 not supported

### ISSUE THREAD

**Issue by lecrams** [esphome/esp-web-tools#320]
Despite what the documentation says, espweb comes with the message ESP32-S3 not supported.

![image](https://user-images.githubusercontent.com/74721082/214556341-f8118e41-cdeb-4fe0-9899-5ac5573790f6.png)

I am trying to flash a lilygo T-camera-S3. The device is in a bootloop with the message invalid header 0xffffff.
The bootloop start with this message:

ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40049b21
invalid header: 0xffffffff
invalid header: 0xffffffff

Any ideas how to solve this?

**Comment by balloob** [comment]
Can you keep the browser console open while you start the installation and screenshot the results ?

**Comment by lecrams** [comment]
On device Dashboard I select install esphome. Then confirm installation (v2022.3.0)
After a few seconds I get:
![image](https://user-images.githubusercontent.com/74721082/214784395-0c70b6a8-c3c6-4c2b-9e41-5cb7b4a1b04d.png)

Back and then select logs & console. 
[esp-web-tools-logs.txt](https://github.com/esphome/esp-web-tools/files/10507245/esp-web-tools-logs.txt)

This gives an empty console window.
Then reset device gives :
![image](https://user-images.githubusercontent.com/74721082/214784551-777e655c-2734-4708-ae82-23667dde0d0b.png)

Hope this is sufficient logging?

**Comment by balloob** [comment]
I meant the console that you see when you click anywhere on the page -> inspect element. Then the browser dev tools open and it has a console tab

**Comment by balloob** [comment]
oh actually, I see what's up here. The ESP Web Tools demo on the website does not have a build for the ESP32 S-3. It's supported if you deploy your own version and provide a build in the manifest.

**Comment by balloob** [comment]
We've updated our demo to now include S3 support 👍

**Comment by lecrams** [comment]
Super! saves me some work. Thanks
