### ISSUE TITLE
[Feature] Install user provided firmware

### ISSUE THREAD

**Issue by Jason2866** [esphome/esp-web-tools#343]
Requested here https://github.com/tasmota/install/issues/8
We have several users asking in Discord wanting to flash a Tasmota firmware (build Online for example with https://github.com/benzino77/tasmocompiler) with the Tasmota Web Installer.

**Comment by balloob** [comment]
That's out of scope for ESP Web Tools. For custom firmware installation, you can refer them to https://espressif.github.io/esptool-js/ or https://web.esphome.io/ (The install action)

**Comment by balloob** [comment]
Also, web flashing is possible on a `localhost` URL. So tasmocompiler could just include esptool-js in their website
