### ISSUE TITLE
Could not install ESPHome on EP1 (ESP32): Failed to open serial port.

### ISSUE THREAD

**Issue by Quentame** [esphome/esp-web-tools#353]
Hi !

I got an EP1 (Everything Presence One) from [Everything Smart Home](https://www.youtube.com/@EverythingSmartHome) ([Hardware overview](https://everythingsmarthome.github.io/everything-presence-one/hardware-overview.html)), and trying to update via the official tool, using ESP Web Tools, [here](https://everythingsmarthome.github.io/everything-presence-one/updating.html), but it's not working.

**How to reproduce**
1. Go to the firmware installation page: https://everythingsmarthome.github.io/everything-presence-one/updating.html
2. Click connect
3. Chrome is displaying this dialog: 
![image](https://user-images.githubusercontent.com/14821482/229122809-5e372758-3ad9-4ba9-bc98-489d9bcf508f.png)
4. Whenever I chose the first or the second option, I got the same Javascript error, with no console logging: `Failed to execute 'open' on 'SerialPort': Failed to open serial port.` 
![image](https://user-images.githubusercontent.com/14821482/229123468-a323d78a-cf98-4764-b62f-ec8866a08086.png)

I also tried on official ESP tools here:
- https://esphome.github.io/esp-web-tools/
- https://web.esphome.io/

==> With the same results.

**Environnement**
- Windows 10 Entreprise 21H2
- Chrome 111
- The cable is passing data + power, verified by connecting an Android phone to my machine.

**Additional informations**
I think the COM3 line while selectiong serial ports was not there at first. Then, Windows installed some kind of driver when I plugged in the EP1, then the line appear.
When having this troubleshouting dialog, I installed CP2102 drivers, but it did not change, even after a reboot. I don't know what kind of chip it is, and I think it would be written in the EP1 doc if I needed to install a driver.
![image](https://user-images.githubusercontent.com/14821482/229124899-9c6149dc-c3d0-4832-9ed7-4274438f5e34.png)

Thanks

**Comment by balloob** [comment]
This is a driver issue. Please contact the manufacturer about what drivers you need to install.
