### ISSUE TITLE
Failed to download manifest

### ISSUE THREAD

**Issue by Lasakro** [esphome/esp-web-tools#366]
I've seen 2 resolutions for this error. Both state: Resolved, add "/" in path folder name and work fine.

1) I goto: https://esphome.github.io/esp-web-tools/ and select connect.
2) I choose the CP2102 for my esp32 in flash mode and again select Connect.

This is where I receive Error Failed to download manifest. What am I missing?

**Comment by jnthas** [comment]
You are not missing anything. It was a misleading update few weeks ago that cause this bug. 
Just wait the PR be merged and it will back to normal
https://github.com/esphome/esp-web-tools/pull/367

**Comment by anubis-code** [comment]
Hi when will this be getting merged as it is still not working

**Comment by drumstick77** [comment]
Hi this is still broken
any update please?

**Comment by jnthas** [comment]
@balloob @jesserockz could you take a look into this, please?

**Comment by drumstick77** [comment]
Thanks @jnthas , I found that by going to https://web.esphome.io/, it seems to be working okay. Just not on the live demo page. Hope that helps

**Comment by jnthas** [comment]
Thanks

**Comment by balloob** [comment]
Sorry for late response. Merged the fix.
