### ISSUE TITLE
[Feature] Flash mode and MCU clock

### ISSUE THREAD

**Issue by Jason2866** [esphome/esp-web-tools#38]
Maybe i missed that but there is no possibility to set Flash Mode (QIO, QOUT, DIO and DOUT)
nor the MCU clock frequency in manifest.json

**Comment by balloob** [comment]
We can't support this because it's not supported upstream https://github.com/NabuCasa/ESP-Web-flasher/ . Once upstream has added support, we can re-open this issue.
