### ISSUE TITLE
[Feature] Detect cdc/USB_SERIAL_JTAG devices so users can just get the cdc firmware flavor automatically

### ISSUE THREAD

**Issue by DTTerastar** [esphome/esp-web-tools#383]
Using CDC requires some build flags to be on to work, so you need a separate firmware file for S3 and C3 that are wired that way.  Right now I need users to pick the cdc version if their hardware is setup to use that for serial.  It would be nice if esp web tools could look at the device/serial chip enough to determine it's using cdc so we can just automatically send the user that version of the firmware (using a different entry in the manifest).

**Comment by TD-er** [comment]
To geralize this a bit more, how can we give back some string using IMPROV which can be used in the manifest?

**Comment by TD-er** [comment]
How should the web flasher then detect these?

**Comment by DTTerastar** [comment]
https://github.com/espressif/esp-idf/issues/9366 Could the stub detect it?

**Comment by TD-er** [comment]
I really don't know if the stub does send out any identifyable info on what serial port is being used.
Would be interesting for sure.
If it does, then the other use cases (flash size and how flash is connected) can perhaps also be implemented as the flasher code can already identify those and the same interface should be used anyway (if it is possible at all) for querying the used serial port.

**Comment by DTTerastar** [comment]
The stub on esptool.py can definitely detect the flash size so it should be possible.

**Comment by DTTerastar** [comment]
Serial port WebSerial VendorID 0x303a ProductID 0x1001 is a hint it's CDC (USB_SERIAL_JTAG).  And there is actually a special handshake for just the CDC version: https://github.com/espressif/esptool-js/pull/54

**Comment by Jason2866** [comment]
Imho wrong place to ask since esp-web-tools uses espressif esptool.js under the hood.
This features needs to be implemented there, if this is done esp-web-tools could use.
Before there is no way to do.

**Comment by Jason2866** [comment]
For project Tasmota we solved differently. No need for different firmwares for CDC and UART.
The code detects if it is connected via CDC, if yes it uses this port, when this check fails UART is used. This feature will be used for all CDC when we release Tasmota based on Arduino 3.0.0
