### ISSUE TITLE
Is it possible to add a translation?

### ISSUE THREAD

**Issue by jaku2019** [esphome/esp-web-tools#407]
Hello,
At the beggining I wanted to thank you for providing such a useful tool.

I would want to help translate this project to Polish. Is it possible?

Best regards,
Jakub

**Comment by balloob** [comment]
ESP Web Tools does not currently support translations.

**Comment by jaku2019** [comment]
> ESP Web Tools does not currently support translations.

Thank you for the information.
Best regards,
Jakub
