### ISSUE TITLE
Firmware file URL

### ISSUE THREAD

**Issue by mrekin** [esphome/esp-web-tools#440]
Hi!
Did not found same question.

I serve page with esp web tool at URL like
`https://domain.com/flasher`

And have 2 API which returns manifest.json and firmware file
```
/api/manifest
/api/firmware
```

So I configure relative path to manifest api 
and, inside manifest, I return relative path to firmware 
`api/firmware`

I found that esp web tool generates _invalid_ full url to firmware like `domain.com/flasher/api/api/firmware` (double _api_)

Is it correct/expected that this code (flash.ts)
`const url = new URL(part.path, manifestURL).toString();`
use **manifest url** as base url nor **location** ?

Now I have to configure firmware path as relative not from base_url but relative from manifest url - looks like not very clear.

---p/s also here other little bug with error text
```
 throw new Error(
        `Downlading firmware ${part.path} failed: ${resp.status}`,
      );
```
Downlading -> Downloading

**Comment by balloob** [comment]
All files referenced in the manifest are resolved relative to the manifest file. That is by design. Update your manifest with absolute files /api/firmware or use relative ../firmware
