### ISSUE TITLE
Is it possible to flash esp-c6?

### ISSUE THREAD

**Issue by BasBaas08** [esphome/esp-web-tools#497]
There is a issue mensioning there should be support for the ESP32-C6 SoC in the latest version. But when i try, it says the board is unsupported. is this a known issue?

the issue metioning it shoudld be possible: https://github.com/esphome/esp-web-tools/issues/455

**Comment by jonasniesner** [comment]
Yes, you cam flash an esp32-C6

**Comment by BasBaas08** [comment]
![Schermafbeelding 2024-09-29 235109](https://github.com/user-attachments/assets/9c49f6ae-5985-44d5-9668-6d803acb52be)

**Comment by BasBaas08** [comment]
I have found that esp-web-tools uses esp-idf 4.4, and support for esp32c6 doesn't start until 5.0. So it's more of a question of when it will be updated to 5.0+

**Comment by EmileSpecialProducts** [comment]
I do not see the Issue, I can program the ESP32-C6.
You can have a try at [this loaction](https://emilespecialproducts.github.io/Turtle-ESP-mouse-jiggler/firmware/upload.html)
and you can find the code at this [location](https://github.com/EmileSpecialProducts/Turtle-ESP-mouse-jiggler)
The only problem i have is that the C6 is not yet supported by platformIO :-(

**Comment by balloob** [comment]
C6 is supported by ESP Web Tools but our example firmware doesn't support it.
