### ISSUE TITLE
Espressif Wi-Fi Provisioning support

### ISSUE THREAD

**Issue by anabolyc** [esphome/esp-web-tools#508]
Hey Folks.

First of all, thanks for the great product. Since I start to use it to self-provision ESP32-based devices, cannot think of anything better.

Currently, I have issues using [improv](https://github.com/improv-wifi) for wifi provisioning within esp-idf project. Documentation does not help much and existing code only works with Arduino as is. I know that ESPHome did manage that, but it is quite hard to port anywhere else since that implementation is baked tight into esphome implementation.

Espressif recently implemented their own [wifi provisioning](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/provisioning/wifi_provisioning.html#overview) mechanism that uses BLE, SoftAP or Console method. The last one being equivalent of Improv-wifi I can only assume. Code is [here](https://github.com/espressif/esp-idf/tree/master/components/wifi_provisioning) and example is [here](https://github.com/espressif/esp-idf/tree/master/examples/provisioning/wifi_prov_mgr) although they do not have console provisioning example just yet.

Would esp-web-tools consider adding Espressif implementation support along with improv-wifi to extend wifi-provisioning possibilities (including future devices)?

**Comment by balloob** [comment]
We're not currently planning on adding support for other provisioning protocols. We created Improv because there was none, and it has now been widely adopted by our communities. It can be implemented on top of any stack being used and is not tied to Espressif or other board vendors.
