### ISSUE TITLE
Add multiple install buttons on the same page

### ISSUE THREAD

**Issue by m1cr0lab** [esphome/esp-web-tools#52]
**First of all, thank you very much 💖 for this indispensable tool!**

How to put several buttons on the same HTML page?

By doing the following, the buttons appear normally on the page:

```html
<esp-web-install-button manifest="manifest_1.json"></esp-web-install-button>
<esp-web-install-button manifest="manifest_2.json"></esp-web-install-button>
<esp-web-install-button manifest="manifest_3.json"></esp-web-install-button>
```

During the first download (with any of the buttons), everything goes well:
the progress bar appears correctly during the whole installation process.

**But when you want to download again (with another button), the progress bar does not appear anymore.** 😕 

Is there anything special to do in this context, or is it a bug?

I thank you in advance for your help.
Steph

**Comment by balloob** [comment]
That's a bug. We are using module-scoped variables which are the same for each instance.

Instead we should attach this info to the button.

The logic is here https://github.com/esphome/esp-web-tools/blob/main/src/start-flash.ts#L9-L15

**Comment by m1cr0lab** [comment]
Thank you very much for this fix!
