### ISSUE TITLE
Add Support for LOLIN S2 Mini

### ISSUE THREAD

**Issue by mawa85** [esphome/esp-web-tools#85]
I tried to flash a LOLIN S2 Mini, but get the error:

Your ESP32-S2 board is not supported.

Board is this one
https://www.wemos.cc/en/latest/s2/s2_mini.html

If you need anything please let me know, happy to support testing.

**Comment by youngd24** [comment]
+1 on this, have the same issue

**Comment by jh-maker** [comment]
Any news on supporting this model? If anybody needs one to implement this model let me know.

**Comment by witnessmenow** [comment]
If you update the manifest to be **ESP32-S2** rather than the ESP32S2 as described on the readme it seems to work

**Comment by balloob** [comment]
Updated docs in 18c2053

In the future, if you notice an issue in the docs, please open a PR.

**Comment by ZanzyTHEbar** [comment]
i've tried this - it tells me that the board is not supported. 
My `manifest.json` file
```json
{
    "name": "OpenIris",
    "version": "2021.11.0",
    "new_install_prompt_erase": true,
    "builds": [
        {
            "chipFamily": "ESP32-S2",
            "parts": [
                {
                    "path": "merged-firmware.bin",
                    "offset": 0
                }
            ]
        }
    ]
}
```
Iam using an `ESPCam` board - funny thing is if i use `ESP32` - it works fine, nothing is wrong with the firmware. Setting it to `ESP32-S2` fails for some reason.

**Comment by TD-er** [comment]
As far as I know, there is no ESP-cam board with an ESP32-S2, so it might be exactly according to specs what you're seeing here.

**Comment by ZanzyTHEbar** [comment]
correct - they use the ESP32-S - i was conflating the versions. Thank you
for the sanity check :)

**Comment by balloob** [comment]
Please no discussion on old issues.
