### ISSUE TITLE
Commands sent to the console not sent to the ESP

### ISSUE THREAD

**Issue by TD-er** [esphome/esp-web-tools#96]
Just tried the new  "Logs" console.
![image](https://user-images.githubusercontent.com/3751318/141181589-93f6d6b9-fc88-412f-80fc-00793bdcfd8c.png)

Really useful and looking nice!
But.. as you can see in the screenshot, I tried to send a few commands to it, but those do not seem to be processed.
Are the commands, or whatever you type to it, being forwarded to the ESP?
And if so, what is used as the line termination?

What does the "send" button do? 

Also after a while (only a few minutes) I got this Framing error:
![image](https://user-images.githubusercontent.com/3751318/141181911-b4519109-ce0f-4a37-9bba-4ea42e8ee30b.png)
So I guess the terminal session somehow got interrupted and does not continue.

The same when pressing the "reset device":
![image](https://user-images.githubusercontent.com/3751318/141182359-5d05a559-d639-47c3-baf3-c9a0d154567c.png)

That data, right after a reset is so useful, so too bad it isn't being captured.
And on top of that, the serial port cannot be opened again, even though this is the only session connected to the serial port:
![image](https://user-images.githubusercontent.com/3751318/141182616-b88794ff-9e54-410c-af87-4575761df2a6.png)

**Comment by balloob** [comment]
Ah, right now we don't use any line ending when sending a command. That's not good.

https://github.com/esphome/esp-web-tools/blob/main/src/components/ewt-console.ts#L184

Would you expect `\r\n` ?

**Comment by TD-er** [comment]
A CRLF is fine, I only check for one and ignore the other, so CRLF is OK.

**Comment by balloob** [comment]
What is convention? Would be good to do the right thing.

**Comment by balloob** [comment]
Fix here https://github.com/esphome/esp-web-tools/pull/97

**Comment by TD-er** [comment]
There is still some `IMPROV` in the command buffer for the first command given:
![image](https://user-images.githubusercontent.com/3751318/141188601-dbb53dc7-b0b2-4385-bfcb-95fce26570a4.png)

**Comment by TD-er** [comment]
Also it is unclear what the "Send" button does or should do

**Comment by balloob** [comment]
The Send button does the same as pressing ENTER

**Comment by TD-er** [comment]
> The Send button does the same as pressing ENTER

Nope, not here in my setup.
